/* Automatically generated.  Do not edit */
/* See the tool/mkopcodec.sh script for details. */
#include "sqliteInt.h"
#if defined(SQLITE_ENABLE_EXPLAIN_COMMENTS) || defined(SQLITE_DEBUG)
# define OpHelp(X) "\0" X
#else
# define OpHelp(X)
#endif
const char *sqlite3OpcodeName(int i){
 static const char *const azName[] = {
    /*   0 */ "Savepoint"        OpHelp(""),
    /*   1 */ "SorterNext"       OpHelp(""),
    /*   2 */ "PrevIfOpen"       OpHelp(""),
    /*   3 */ "NextIfOpen"       OpHelp(""),
    /*   4 */ "Prev"             OpHelp(""),
    /*   5 */ "Or"               OpHelp("r[P3]=(r[P1] || r[P2])"),
    /*   6 */ "And"              OpHelp("r[P3]=(r[P1] && r[P2])"),
    /*   7 */ "Not"              OpHelp("r[P2]= !r[P1]"),
    /*   8 */ "Next"             OpHelp(""),
    /*   9 */ "Goto"             OpHelp(""),
    /*  10 */ "Gosub"            OpHelp(""),
    /*  11 */ "InitCoroutine"    OpHelp(""),
    /*  12 */ "Yield"            OpHelp(""),
    /*  13 */ "Ne"               OpHelp("IF r[P3]!=r[P1]"),
    /*  14 */ "Eq"               OpHelp("IF r[P3]==r[P1]"),
    /*  15 */ "Gt"               OpHelp("IF r[P3]>r[P1]"),
    /*  16 */ "Le"               OpHelp("IF r[P3]<=r[P1]"),
    /*  17 */ "Lt"               OpHelp("IF r[P3]<r[P1]"),
    /*  18 */ "Ge"               OpHelp("IF r[P3]>=r[P1]"),
    /*  19 */ "ElseNotEq"        OpHelp(""),
    /*  20 */ "BitAnd"           OpHelp("r[P3]=r[P1]&r[P2]"),
    /*  21 */ "BitOr"            OpHelp("r[P3]=r[P1]|r[P2]"),
    /*  22 */ "ShiftLeft"        OpHelp("r[P3]=r[P2]<<r[P1]"),
    /*  23 */ "ShiftRight"       OpHelp("r[P3]=r[P2]>>r[P1]"),
    /*  24 */ "Add"              OpHelp("r[P3]=r[P1]+r[P2]"),
    /*  25 */ "Subtract"         OpHelp("r[P3]=r[P2]-r[P1]"),
    /*  26 */ "Multiply"         OpHelp("r[P3]=r[P1]*r[P2]"),
    /*  27 */ "Divide"           OpHelp("r[P3]=r[P2]/r[P1]"),
    /*  28 */ "Remainder"        OpHelp("r[P3]=r[P2]%r[P1]"),
    /*  29 */ "Concat"           OpHelp("r[P3]=r[P2]+r[P1]"),
    /*  30 */ "MustBeInt"        OpHelp(""),
    /*  31 */ "BitNot"           OpHelp("r[P1]= ~r[P1]"),
    /*  32 */ "Jump"             OpHelp(""),
    /*  33 */ "Once"             OpHelp(""),
    /*  34 */ "If"               OpHelp(""),
    /*  35 */ "IfNot"            OpHelp(""),
    /*  36 */ "SeekLT"           OpHelp("key=r[P3@P4]"),
    /*  37 */ "SeekLE"           OpHelp("key=r[P3@P4]"),
    /*  38 */ "SeekGE"           OpHelp("key=r[P3@P4]"),
    /*  39 */ "SeekGT"           OpHelp("key=r[P3@P4]"),
    /*  40 */ "NoConflict"       OpHelp("key=r[P3@P4]"),
    /*  41 */ "NotFound"         OpHelp("key=r[P3@P4]"),
    /*  42 */ "Found"            OpHelp("key=r[P3@P4]"),
    /*  43 */ "Last"             OpHelp(""),
    /*  44 */ "SorterSort"       OpHelp(""),
    /*  45 */ "Sort"             OpHelp(""),
    /*  46 */ "Rewind"           OpHelp(""),
    /*  47 */ "IdxLE"            OpHelp("key=r[P3@P4]"),
    /*  48 */ "IdxGT"            OpHelp("key=r[P3@P4]"),
    /*  49 */ "IdxLT"            OpHelp("key=r[P3@P4]"),
    /*  50 */ "IdxGE"            OpHelp("key=r[P3@P4]"),
    /*  51 */ "Program"          OpHelp(""),
    /*  52 */ "FkIfZero"         OpHelp("if fkctr[P1]==0 goto P2"),
    /*  53 */ "IfPos"            OpHelp("if r[P1]>0 then r[P1]-=P3, goto P2"),
    /*  54 */ "IfNotZero"        OpHelp("if r[P1]!=0 then r[P1]--, goto P2"),
    /*  55 */ "DecrJumpZero"     OpHelp("if (--r[P1])==0 goto P2"),
    /*  56 */ "Init"             OpHelp("Start at P2"),
    /*  57 */ "Return"           OpHelp(""),
    /*  58 */ "EndCoroutine"     OpHelp(""),
    /*  59 */ "HaltIfNull"       OpHelp("if r[P3]=null halt"),
    /*  60 */ "Halt"             OpHelp(""),
    /*  61 */ "Integer"          OpHelp("r[P2]=P1"),
    /*  62 */ "Bool"             OpHelp("r[P2]=P1"),
    /*  63 */ "Int64"            OpHelp("r[P2]=P4"),
    /*  64 */ "String"           OpHelp("r[P2]='P4' (len=P1)"),
    /*  65 */ "NextAutoincValue" OpHelp("r[P2] = next value from space sequence, which pageno is r[P1]"),
    /*  66 */ "Null"             OpHelp("r[P2..P3]=NULL"),
    /*  67 */ "SoftNull"         OpHelp("r[P1]=NULL"),
    /*  68 */ "Blob"             OpHelp("r[P2]=P4 (len=P1, subtype=P3)"),
    /*  69 */ "Variable"         OpHelp("r[P2]=parameter(P1,P4)"),
    /*  70 */ "Move"             OpHelp("r[P2@P3]=r[P1@P3]"),
    /*  71 */ "Copy"             OpHelp("r[P2@P3+1]=r[P1@P3+1]"),
    /*  72 */ "String8"          OpHelp("r[P2]='P4'"),
    /*  73 */ "SCopy"            OpHelp("r[P2]=r[P1]"),
    /*  74 */ "IntCopy"          OpHelp("r[P2]=r[P1]"),
    /*  75 */ "ResultRow"        OpHelp("output=r[P1@P2]"),
    /*  76 */ "CollSeq"          OpHelp(""),
    /*  77 */ "Function0"        OpHelp("r[P3]=func(r[P2@P5])"),
    /*  78 */ "Function"         OpHelp("r[P3]=func(r[P2@P5])"),
    /*  79 */ "AddImm"           OpHelp("r[P1]=r[P1]+P2"),
    /*  80 */ "RealAffinity"     OpHelp(""),
    /*  81 */ "Cast"             OpHelp("affinity(r[P1])"),
    /*  82 */ "Permutation"      OpHelp(""),
    /*  83 */ "Compare"          OpHelp("r[P1@P3] <-> r[P2@P3]"),
    /*  84 */ "Column"           OpHelp("r[P3]=PX"),
    /*  85 */ "Affinity"         OpHelp("affinity(r[P1@P2])"),
    /*  86 */ "MakeRecord"       OpHelp("r[P3]=mkrec(r[P1@P2])"),
    /*  87 */ "Count"            OpHelp("r[P2]=count()"),
    /*  88 */ "CheckViewReferences" OpHelp("r[P1] = space id"),
    /*  89 */ "TransactionBegin" OpHelp(""),
    /*  90 */ "TransactionCommit" OpHelp(""),
    /*  91 */ "TransactionRollback" OpHelp(""),
    /*  92 */ "TTransaction"     OpHelp(""),
    /*  93 */ "IteratorReopen"   OpHelp("index id = P2, space ptr = P4"),
    /*  94 */ "IteratorOpen"     OpHelp("index id = P2, space ptr = P4 or reg[P3]"),
    /*  95 */ "OpenTEphemeral"   OpHelp(""),
    /*  96 */ "SorterOpen"       OpHelp(""),
    /*  97 */ "SequenceTest"     OpHelp("if (cursor[P1].ctr++) pc = P2"),
    /*  98 */ "OpenPseudo"       OpHelp("P3 columns in r[P2]"),
    /*  99 */ "Close"            OpHelp(""),
    /* 100 */ "ColumnsUsed"      OpHelp(""),
    /* 101 */ "Sequence"         OpHelp("r[P2]=cursor[P1].ctr++"),
    /* 102 */ "NextSequenceId"   OpHelp("r[P2]=get_max(_sequence)"),
    /* 103 */ "NextIdEphemeral"  OpHelp("r[P2]=get_next_rowid(space[P1])"),
    /* 104 */ "FCopy"            OpHelp("reg[P2@cur_frame]= reg[P1@root_frame(OPFLAG_SAME_FRAME)]"),
    /* 105 */ "Delete"           OpHelp(""),
    /* 106 */ "ResetCount"       OpHelp(""),
    /* 107 */ "SorterCompare"    OpHelp("if key(P1)!=trim(r[P3],P4) goto P2"),
    /* 108 */ "SorterData"       OpHelp("r[P2]=data"),
    /* 109 */ "RowData"          OpHelp("r[P2]=data"),
    /* 110 */ "NullRow"          OpHelp(""),
    /* 111 */ "SorterInsert"     OpHelp("key=r[P2]"),
    /* 112 */ "IdxReplace"       OpHelp(""),
    /* 113 */ "IdxInsert"        OpHelp("key=r[P1]"),
    /* 114 */ "SInsert"          OpHelp("space id = P1, key = r[P3], on error goto P2"),
    /* 115 */ "SDelete"          OpHelp("space id = P1, key = r[P2]"),
    /* 116 */ "Real"             OpHelp("r[P2]=P4"),
    /* 117 */ "IdxDelete"        OpHelp("key=r[P2@P3]"),
    /* 118 */ "Clear"            OpHelp("space id = P1"),
    /* 119 */ "ResetSorter"      OpHelp(""),
    /* 120 */ "RenameTable"      OpHelp("P1 = space_id, P4 = name"),
    /* 121 */ "LoadAnalysis"     OpHelp(""),
    /* 122 */ "Param"            OpHelp(""),
    /* 123 */ "FkCounter"        OpHelp("fkctr[P1]+=P2"),
    /* 124 */ "OffsetLimit"      OpHelp("if r[P1]>0 then r[P2]=r[P1]+max(0,r[P3]) else r[P2]=(-1)"),
    /* 125 */ "AggStep0"         OpHelp("accum=r[P3] step(r[P2@P5])"),
    /* 126 */ "AggStep"          OpHelp("accum=r[P3] step(r[P2@P5])"),
    /* 127 */ "AggFinal"         OpHelp("accum=r[P1] N=P2"),
    /* 128 */ "Expire"           OpHelp(""),
    /* 129 */ "IncMaxid"         OpHelp(""),
    /* 130 */ "Noop"             OpHelp(""),
    /* 131 */ "Explain"          OpHelp(""),
    /* 132 */ "NotUsed_132"      OpHelp(""),
    /* 133 */ "NotUsed_133"      OpHelp(""),
    /* 134 */ "NotUsed_134"      OpHelp(""),
    /* 135 */ "NotUsed_135"      OpHelp(""),
    /* 136 */ "NotUsed_136"      OpHelp(""),
    /* 137 */ "NotUsed_137"      OpHelp(""),
    /* 138 */ "NotUsed_138"      OpHelp(""),
    /* 139 */ "NotUsed_139"      OpHelp(""),
    /* 140 */ "NotUsed_140"      OpHelp(""),
    /* 141 */ "NotUsed_141"      OpHelp(""),
    /* 142 */ "NotUsed_142"      OpHelp(""),
    /* 143 */ "NotUsed_143"      OpHelp(""),
    /* 144 */ "NotUsed_144"      OpHelp(""),
    /* 145 */ "NotUsed_145"      OpHelp(""),
    /* 146 */ "NotUsed_146"      OpHelp(""),
    /* 147 */ "NotUsed_147"      OpHelp(""),
    /* 148 */ "NotUsed_148"      OpHelp(""),
    /* 149 */ "NotUsed_149"      OpHelp(""),
    /* 150 */ "NotUsed_150"      OpHelp(""),
    /* 151 */ "IsNull"           OpHelp("if r[P1]==NULL goto P2"),
    /* 152 */ "NotNull"          OpHelp("if r[P1]!=NULL goto P2"),
  };
  return azName[i];
}
