#define TK_SEMI                             1
#define TK_EXPLAIN                          2
#define TK_QUERY                            3
#define TK_PLAN                             4
#define TK_OR                               5
#define TK_AND                              6
#define TK_NOT                              7
#define TK_IS                               8
#define TK_MATCH                            9
#define TK_LIKE_KW                         10
#define TK_BETWEEN                         11
#define TK_IN                              12
#define TK_NE                              13
#define TK_EQ                              14
#define TK_GT                              15
#define TK_LE                              16
#define TK_LT                              17
#define TK_GE                              18
#define TK_ESCAPE                          19
#define TK_BITAND                          20
#define TK_BITOR                           21
#define TK_LSHIFT                          22
#define TK_RSHIFT                          23
#define TK_PLUS                            24
#define TK_MINUS                           25
#define TK_STAR                            26
#define TK_SLASH                           27
#define TK_REM                             28
#define TK_CONCAT                          29
#define TK_COLLATE                         30
#define TK_BITNOT                          31
#define TK_START                           32
#define TK_TRANSACTION                     33
#define TK_COMMIT                          34
#define TK_ROLLBACK                        35
#define TK_SAVEPOINT                       36
#define TK_RELEASE                         37
#define TK_TO                              38
#define TK_TABLE                           39
#define TK_CREATE                          40
#define TK_IF                              41
#define TK_EXISTS                          42
#define TK_LP                              43
#define TK_RP                              44
#define TK_AS                              45
#define TK_COMMA                           46
#define TK_ID                              47
#define TK_INDEXED                         48
#define TK_ABORT                           49
#define TK_ACTION                          50
#define TK_ADD                             51
#define TK_AFTER                           52
#define TK_AUTOINCREMENT                   53
#define TK_BEFORE                          54
#define TK_CASCADE                         55
#define TK_CONFLICT                        56
#define TK_DEFERRED                        57
#define TK_END                             58
#define TK_FAIL                            59
#define TK_IGNORE                          60
#define TK_INITIALLY                       61
#define TK_INSTEAD                         62
#define TK_NO                              63
#define TK_KEY                             64
#define TK_OFFSET                          65
#define TK_RAISE                           66
#define TK_REPLACE                         67
#define TK_RESTRICT                        68
#define TK_RENAME                          69
#define TK_CTIME_KW                        70
#define TK_ANY                             71
#define TK_STRING                          72
#define TK_CONSTRAINT                      73
#define TK_DEFAULT                         74
#define TK_NULL                            75
#define TK_PRIMARY                         76
#define TK_UNIQUE                          77
#define TK_CHECK                           78
#define TK_REFERENCES                      79
#define TK_AUTOINCR                        80
#define TK_ON                              81
#define TK_INSERT                          82
#define TK_DELETE                          83
#define TK_UPDATE                          84
#define TK_SIMPLE                          85
#define TK_PARTIAL                         86
#define TK_FULL                            87
#define TK_SET                             88
#define TK_DEFERRABLE                      89
#define TK_IMMEDIATE                       90
#define TK_FOREIGN                         91
#define TK_DROP                            92
#define TK_VIEW                            93
#define TK_UNION                           94
#define TK_ALL                             95
#define TK_EXCEPT                          96
#define TK_INTERSECT                       97
#define TK_SELECT                          98
#define TK_VALUES                          99
#define TK_DISTINCT                       100
#define TK_DOT                            101
#define TK_FROM                           102
#define TK_JOIN_KW                        103
#define TK_JOIN                           104
#define TK_BY                             105
#define TK_USING                          106
#define TK_ORDER                          107
#define TK_ASC                            108
#define TK_DESC                           109
#define TK_GROUP                          110
#define TK_HAVING                         111
#define TK_LIMIT                          112
#define TK_TRUNCATE                       113
#define TK_WHERE                          114
#define TK_INTO                           115
#define TK_FLOAT                          116
#define TK_BLOB                           117
#define TK_INTEGER                        118
#define TK_VARIABLE                       119
#define TK_CAST                           120
#define TK_DATE                           121
#define TK_DATETIME                       122
#define TK_CHAR                           123
#define TK_CASE                           124
#define TK_WHEN                           125
#define TK_THEN                           126
#define TK_ELSE                           127
#define TK_INDEX                          128
#define TK_PRAGMA                         129
#define TK_BEGIN                          130
#define TK_TRIGGER                        131
#define TK_OF                             132
#define TK_FOR                            133
#define TK_EACH                           134
#define TK_ROW                            135
#define TK_ANALYZE                        136
#define TK_ALTER                          137
#define TK_WITH                           138
#define TK_RECURSIVE                      139
#define TK_TEXT                           140
#define TK_TIME                           141
#define TK_VARCHAR                        142
#define TK_REAL                           143
#define TK_DOUBLE                         144
#define TK_INT                            145
#define TK_DECIMAL                        146
#define TK_NUMERIC                        147
#define TK_NUM                            148
#define TK_STANDARD                       149
#define TK_TO_TEXT                        150
#define TK_ISNULL                         151
#define TK_NOTNULL                        152
#define TK_TO_BLOB                        153
#define TK_TO_NUMERIC                     154
#define TK_TO_INT                         155
#define TK_TO_REAL                        156
#define TK_END_OF_FILE                    157
#define TK_UNCLOSED_STRING                158
#define TK_FUNCTION                       159
#define TK_COLUMN                         160
#define TK_AGG_FUNCTION                   161
#define TK_AGG_COLUMN                     162
#define TK_UMINUS                         163
#define TK_UPLUS                          164
#define TK_REGISTER                       165
#define TK_VECTOR                         166
#define TK_SELECT_COLUMN                  167
#define TK_ASTERISK                       168
#define TK_SPAN                           169
#define TK_SPACE                          170
#define TK_ILLEGAL                        171

/* The token codes above must all fit in 8 bits */
#define TKFLG_MASK           0xff  

/* Flags that can be added to a token code when it is not
** being stored in a u8: */
#define TKFLG_DONTFOLD       0x100  /* Omit constant folding optimizations */
